# Generated by Django 4.2.5 on 2024-10-30 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deputados', '0001_initial'),
        ('vereadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vereador',
            name='deputado',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eleitores', to='deputados.deputado'),
        ),
    ]
